# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/config"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/eureka"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/eurekaclient1"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/eurekaclient2"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/gateway"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/micro-azure"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/micro1"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/micro2"
    schedule:
      interval: "weekly"
